### ISSUE TITLE
how to use your Clover EFI for use Ventura

### ISSUE THREAD

**Issue by hagiwidyatama** [AppleBreak1/EP45-UD3P-Customac#1]
hi applebreak , how to use your Clover EFI for use Ventura, I was use Monterey with clover , I was use clover because more fast on my G41 chipset. 

Thanks

**Comment by AppleBreak1** [comment]
Hi,

Try updating to Clover v5151 then follow the [requirements](https://github.com/AppleBreak1/EP45-UD3P-Customac/tree/main/Install%20macOS%20Ventura%2013.0) for Ventura.

It's been a while since I've used Clover really. But out of curiosity, I did try Clover to boot(Not install) Ventura with success.
<img width="892" alt="Screenshot 2023-03-02 at 12 54 55 PM" src="https://user-images.githubusercontent.com/97265013/222552195-e6cb86b7-0b85-4550-8a02-75df8aeaf048.png">

You can give it a try. But, I assume it might be more difficult for you with G41 chipset.
